// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nvxapp.server.data.Infrastructure;

#nullable disable

namespace nvxapp.server.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516090558_GestionePresenze_init")]
    partial class GestionePresenze_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "public");
                });

            modelBuilder.Entity("Par_OrarioPar_ProfiloOrarioGG", b =>
                {
                    b.Property<int>("Par_OrarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Par_ProfiloOrarioGGId")
                        .HasColumnType("integer");

                    b.HasKey("Par_OrarioId", "Par_ProfiloOrarioGGId");

                    b.HasIndex("Par_ProfiloOrarioGGId");

                    b.ToTable("Par_OrarioPar_ProfiloOrarioGG", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdFinancialAdvisor")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descrizione")
                        .IsUnique();

                    b.HasIndex("IdFinancialAdvisor");

                    b.ToTable("Company", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Descrizione")
                        .IsUnique();

                    b.ToTable("Dealer", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.FinancialAdvisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdDealer")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Descrizione")
                        .IsUnique();

                    b.HasIndex("IdDealer");

                    b.ToTable("FinancialAdvisor", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.UserCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<bool>("MainUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAspNetUsers");

                    b.HasIndex("IdCompany", "IdAspNetUsers")
                        .IsUnique();

                    b.ToTable("UserCompany", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.UserDealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdDealer")
                        .HasColumnType("integer");

                    b.Property<bool>("MainUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAspNetUsers");

                    b.HasIndex("IdDealer", "IdAspNetUsers")
                        .IsUnique();

                    b.ToTable("UserDealer", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.UserFinancialAdvisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdFinancialAdvisor")
                        .HasColumnType("integer");

                    b.Property<bool>("MainUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAspNetUsers");

                    b.HasIndex("IdFinancialAdvisor", "IdAspNetUsers")
                        .IsUnique();

                    b.ToTable("UserFinancialAdvisor", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany")
                        .IsUnique();

                    b.ToTable("Az_Anagrafica", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Cfg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovazioneTipo")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica")
                        .IsUnique();

                    b.ToTable("Az_Cfg", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Sedi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica");

                    b.ToTable("Az_Sedi", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediReparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Sedi")
                        .HasColumnType("integer");

                    b.Property<int?>("IdAz_SediReparto")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Sedi");

                    b.HasIndex("IdAz_SediReparto");

                    b.ToTable("Az_SediReparto", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediRepartoAttivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_SediReparto")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_SediReparto");

                    b.ToTable("Az_SediRepartoAttivita", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediRepartoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalZOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataAl")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataDal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EnabledToApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdAz_SediReparto")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAspNetUsers");

                    b.HasIndex("IdAz_SediReparto");

                    b.ToTable("Az_SediRepartoUser", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_Anagrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAspNetUsers")
                        .IsUnique();

                    b.ToTable("Dip_Anagrafica", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Causali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdDip_RapportoLavoro")
                        .HasColumnType("integer");

                    b.Property<int>("IdPar_Causali")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_RapportoLavoro");

                    b.HasIndex("IdPar_Causali");

                    b.ToTable("Dip_GG_Causali", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Giustificativi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan?>("From")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("Hours")
                        .HasColumnType("interval");

                    b.Property<int?>("IdDip_GG_Richiesta")
                        .HasColumnType("integer");

                    b.Property<int>("IdDip_RapportoLavoro")
                        .HasColumnType("integer");

                    b.Property<int>("IdJustificationType")
                        .HasColumnType("integer");

                    b.Property<int>("IdPar_Giustificativi")
                        .HasColumnType("integer");

                    b.Property<int>("InputType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RichiestaStato")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_GG_Richiesta");

                    b.HasIndex("IdDip_RapportoLavoro");

                    b.HasIndex("IdPar_Giustificativi");

                    b.ToTable("Dip_GG_Giustificativi", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_NotaSpesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdDip_GG_Richiesta")
                        .HasColumnType("integer");

                    b.Property<int>("IdDip_RapportoLavoro")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RichiestaStato")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_GG_Richiesta");

                    b.HasIndex("IdDip_RapportoLavoro");

                    b.ToTable("Dip_GG_NotaSpese", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Richiesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataA")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dati")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdDip_RapportoLavoro")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RevocaApprovazioneData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RevocaStato")
                        .HasColumnType("integer");

                    b.Property<string>("RichiestaApprovazioneData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RichiestaStato")
                        .HasColumnType("integer");

                    b.Property<int>("RichiestaTipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_RapportoLavoro");

                    b.ToTable("Dip_GG_Richieste", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Timbratura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GiornoCompetenza")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdDip_GG_Richiesta")
                        .HasColumnType("integer");

                    b.Property<int>("IdDip_RapportoLavoro")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RichiestaStato")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timbratura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TimbraturaArrotondata")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TimbraturaOriginale")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TimbraturaTipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_GG_Richiesta");

                    b.HasIndex("IdDip_RapportoLavoro");

                    b.ToTable("Dip_GG_Timbrature", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_ProfiloOrario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Al")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Dal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdDip_RapportoLavoro")
                        .HasColumnType("integer");

                    b.Property<int?>("IdPar_ProfiloOrario")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumGiornoPartenzaCiclo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_RapportoLavoro");

                    b.HasIndex("IdPar_ProfiloOrario");

                    b.ToTable("Dip_ProfiloOrario", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataAss")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataLic")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdDip_Anagrafica")
                        .HasColumnType("integer")
                        .HasColumnName("IdDip_Anagrafica");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdDip_Anagrafica");

                    b.ToTable("Dip_RapportoLavoro", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Arrotondamenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("Alle")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("ArrotondamentoTipo")
                        .HasColumnType("integer");

                    b.Property<int?>("ArrotondamentoValore")
                        .HasColumnType("integer");

                    b.Property<int?>("ArrotondamentoVerso")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeOnly?>("Dalle")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica");

                    b.ToTable("Par_Arrotondamenti", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Orario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica");

                    b.ToTable("Par_Orario", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_OrarioIntervalloHH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("Alle")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeOnly?>("Dalle")
                        .HasColumnType("time without time zone");

                    b.Property<int>("IdPar_Orario")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdPar_Orario");

                    b.ToTable("Par_ProfiloOrarioIntervalloHH", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumGiorniCiclo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica");

                    b.ToTable("Par_ProfiloOrario", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrarioGG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdPar_ProfiloOrario")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdPar_ProfiloOrario");

                    b.ToTable("Par_ProfiloOrarioGG", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.MyTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Descrizione")
                        .IsUnique();

                    b.ToTable("MyTable", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Par_Causali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica");

                    b.ToTable("Par_Causali", "public");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Par_Giustificativi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ChangeUser")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAz_Anagrafica")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TextColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("TipoInput")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAz_Anagrafica");

                    b.ToTable("Par_Giustificativi", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Par_OrarioPar_ProfiloOrarioGG", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Orario", null)
                        .WithMany()
                        .HasForeignKey("Par_OrarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrarioGG", null)
                        .WithMany()
                        .HasForeignKey("Par_ProfiloOrarioGGId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.Company", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.FinancialAdvisor", "FinancialAdvisorNavigation")
                        .WithMany("Company")
                        .HasForeignKey("IdFinancialAdvisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialAdvisorNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.FinancialAdvisor", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.Dealer", "DealerNavigation")
                        .WithMany("FinancialAdvisor")
                        .HasForeignKey("IdDealer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DealerNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.UserCompany", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", "AspNetUsersNavigation")
                        .WithMany("UserCompany")
                        .HasForeignKey("IdAspNetUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Public.Company", "CompanyNavigation")
                        .WithMany("UserCompany")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUsersNavigation");

                    b.Navigation("CompanyNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.UserDealer", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", "AspNetUsersNavigation")
                        .WithMany("UserDealer")
                        .HasForeignKey("IdAspNetUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Public.Dealer", "DealerNavigation")
                        .WithMany("UserDealer")
                        .HasForeignKey("IdDealer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUsersNavigation");

                    b.Navigation("DealerNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.UserFinancialAdvisor", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", "AspNetUsersNavigation")
                        .WithMany("UserFinancialAdvisor")
                        .HasForeignKey("IdAspNetUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Public.FinancialAdvisor", "FinancialAdvisorNavigation")
                        .WithMany("UserFinancialAdvisor")
                        .HasForeignKey("IdFinancialAdvisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUsersNavigation");

                    b.Navigation("FinancialAdvisorNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.Company", "CompanyNavigation")
                        .WithOne("Az_Anagrafica")
                        .HasForeignKey("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Cfg", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithOne("Az_Cfg")
                        .HasForeignKey("nvxapp.server.data.Entities.Tenant.Az_Cfg", "IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Sedi", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithMany("Az_Sedi")
                        .HasForeignKey("IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediReparto", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Sedi", "Az_SediNavigation")
                        .WithMany("Az_Reparto")
                        .HasForeignKey("IdAz_Sedi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_SediReparto", "Az_SediRepartoNavigation")
                        .WithMany("Az_SediReparto_Sub")
                        .HasForeignKey("IdAz_SediReparto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Az_SediNavigation");

                    b.Navigation("Az_SediRepartoNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediRepartoAttivita", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_SediReparto", "Az_SediRepartoNavigation")
                        .WithMany("Az_SediRepartoAttivita")
                        .HasForeignKey("IdAz_SediReparto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_SediRepartoNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediRepartoUser", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", "AspNetUsersNavigation")
                        .WithMany()
                        .HasForeignKey("IdAspNetUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_SediReparto", "Az_SediRepartoNavigation")
                        .WithMany("Az_SediRepartoUser")
                        .HasForeignKey("IdAz_SediReparto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUsersNavigation");

                    b.Navigation("Az_SediRepartoNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_Anagrafica", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Public.ApplicationUser", "AspNetUsersNavigation")
                        .WithOne("Dip_Anagrafica")
                        .HasForeignKey("nvxapp.server.data.Entities.Tenant.Dip_Anagrafica", "IdAspNetUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUsersNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Causali", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", "Dip_RapportoLavoroNavigation")
                        .WithMany("Dip_GG_Causali")
                        .HasForeignKey("IdDip_RapportoLavoro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Par_Causali", "Par_CausaliNavigation")
                        .WithMany("Dip_GG_Causali")
                        .HasForeignKey("IdPar_Causali")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dip_RapportoLavoroNavigation");

                    b.Navigation("Par_CausaliNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Giustificativi", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_GG_Richiesta", "Dip_RichiestaNavigation")
                        .WithMany("Dip_GG_Giustificativi")
                        .HasForeignKey("IdDip_GG_Richiesta")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", "Dip_RapportoLavoroNavigation")
                        .WithMany("Dip_GG_Giustificativi")
                        .HasForeignKey("IdDip_RapportoLavoro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Par_Giustificativi", "Par_GiustificativiNavigation")
                        .WithMany("Dip_GG_Giustificativi")
                        .HasForeignKey("IdPar_Giustificativi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dip_RapportoLavoroNavigation");

                    b.Navigation("Dip_RichiestaNavigation");

                    b.Navigation("Par_GiustificativiNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_NotaSpesa", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_GG_Richiesta", "Dip_GG_RichiestaNavigation")
                        .WithMany("Dip_GG_NotaSpesa")
                        .HasForeignKey("IdDip_GG_Richiesta")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", "Dip_RapportoLavoroNavigation")
                        .WithMany("Dip_GG_NotaSpesa")
                        .HasForeignKey("IdDip_RapportoLavoro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dip_GG_RichiestaNavigation");

                    b.Navigation("Dip_RapportoLavoroNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Richiesta", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", "Dip_RapportoLavoroNavigation")
                        .WithMany("Dip_GG_Richiesta")
                        .HasForeignKey("IdDip_RapportoLavoro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dip_RapportoLavoroNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Timbratura", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_GG_Richiesta", "Dip_RichiestaNavigation")
                        .WithMany("Dip_GG_Timbratura")
                        .HasForeignKey("IdDip_GG_Richiesta")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", "Dip_RapportoLavoroNavigation")
                        .WithMany("Dip_GG_Timbratura")
                        .HasForeignKey("IdDip_RapportoLavoro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dip_RapportoLavoroNavigation");

                    b.Navigation("Dip_RichiestaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_ProfiloOrario", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", "Dip_RapportoLavoroNavigation")
                        .WithMany("Dip_ProfiloOrario")
                        .HasForeignKey("IdDip_RapportoLavoro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrario", "Par_ProfiloOrarioNavigation")
                        .WithMany("Dip_ProfiloOrario")
                        .HasForeignKey("IdPar_ProfiloOrario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dip_RapportoLavoroNavigation");

                    b.Navigation("Par_ProfiloOrarioNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Dip_Anagrafica", "Dip_AnagraficaNavigation")
                        .WithMany("Dip_RapportoLavoro")
                        .HasForeignKey("IdDip_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dip_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Arrotondamenti", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithMany("Par_Arrotondamenti")
                        .HasForeignKey("IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Orario", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithMany("Par_Orario")
                        .HasForeignKey("IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_OrarioIntervalloHH", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Orario", "Par_OrarioNavigation")
                        .WithMany("Par_OrarioIntervalloHH")
                        .HasForeignKey("IdPar_Orario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Par_OrarioNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrario", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithMany("Par_ProfiloOrario")
                        .HasForeignKey("IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrarioGG", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrario", "Par_ProfiloOrarioNavigation")
                        .WithMany("Par_ProfiloOrarioGG")
                        .HasForeignKey("IdPar_ProfiloOrario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Par_ProfiloOrarioNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Par_Causali", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithMany("Par_Causali")
                        .HasForeignKey("IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Par_Giustificativi", b =>
                {
                    b.HasOne("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", "Az_AnagraficaNavigation")
                        .WithMany("Par_Giustificativi")
                        .HasForeignKey("IdAz_Anagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Az_AnagraficaNavigation");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.ApplicationUser", b =>
                {
                    b.Navigation("Dip_Anagrafica");

                    b.Navigation("UserCompany");

                    b.Navigation("UserDealer");

                    b.Navigation("UserFinancialAdvisor");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.Company", b =>
                {
                    b.Navigation("Az_Anagrafica");

                    b.Navigation("UserCompany");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.Dealer", b =>
                {
                    b.Navigation("FinancialAdvisor");

                    b.Navigation("UserDealer");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Public.FinancialAdvisor", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("UserFinancialAdvisor");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Anagrafica", b =>
                {
                    b.Navigation("Az_Cfg");

                    b.Navigation("Az_Sedi");

                    b.Navigation("Par_Arrotondamenti");

                    b.Navigation("Par_Causali");

                    b.Navigation("Par_Giustificativi");

                    b.Navigation("Par_Orario");

                    b.Navigation("Par_ProfiloOrario");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_Sedi", b =>
                {
                    b.Navigation("Az_Reparto");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Az_SediReparto", b =>
                {
                    b.Navigation("Az_SediRepartoAttivita");

                    b.Navigation("Az_SediRepartoUser");

                    b.Navigation("Az_SediReparto_Sub");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_Anagrafica", b =>
                {
                    b.Navigation("Dip_RapportoLavoro");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_GG_Richiesta", b =>
                {
                    b.Navigation("Dip_GG_Giustificativi");

                    b.Navigation("Dip_GG_NotaSpesa");

                    b.Navigation("Dip_GG_Timbratura");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Dip_RapportoLavoro", b =>
                {
                    b.Navigation("Dip_GG_Causali");

                    b.Navigation("Dip_GG_Giustificativi");

                    b.Navigation("Dip_GG_NotaSpesa");

                    b.Navigation("Dip_GG_Richiesta");

                    b.Navigation("Dip_GG_Timbratura");

                    b.Navigation("Dip_ProfiloOrario");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_Orario", b =>
                {
                    b.Navigation("Par_OrarioIntervalloHH");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.GestionePresenze.Par_ProfiloOrario", b =>
                {
                    b.Navigation("Dip_ProfiloOrario");

                    b.Navigation("Par_ProfiloOrarioGG");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Par_Causali", b =>
                {
                    b.Navigation("Dip_GG_Causali");
                });

            modelBuilder.Entity("nvxapp.server.data.Entities.Tenant.Par_Giustificativi", b =>
                {
                    b.Navigation("Dip_GG_Giustificativi");
                });
#pragma warning restore 612, 618
        }
    }
}
